In [3]:
from sklearn.feature_extraction.text import CountVectorizer
#corpus: 15 tweets using Omicron as the query (Jan 32, 2022)
corpus = ["DrCChambers RT @CIHR_IRSC: In light of the disruptions caused by the Omicron variant of #Covid19, CIHR is extending the registration and application de…",
"sealsoftheend Japan's Kowa says Ivermectin showed 'antiviral effect' against Omicron https://t.co/mKKY24WeQV",
"SVictor70973566 RT @EricTopol: Why is Omicron so hyper-transmissible? It's not related to high viral load in the upper airway, as shown by 2 recent studies…",
"freethinkfacts RT @yaneerbaryam: Actual cases of reinfection by Omicron are so widespread they are manifest to anyone who is not closing their eyes: 10/…",
"lsoril RT @CIHR_IRSC: In light of the disruptions caused by the Omicron variant of #Covid19, CIHR is extending the registration and application de…",
"pompey1977 RT @AllisonPearson: How can people not get it? Omicron’s advantage over Delta is it evades the vaccine. Everyone is going to get Omicron…",
"freethinkfacts RT @yaneerbaryam: Taken together, our results suggest that Omicron-induced immunity may not be sufficient to prevent infection from anothe…",
"SteveBennett15 RT @EricTopol: Anyone who thinks that vaccines aren't working against Omicron might want to review the data https://t.co/9bHYdKxz8u https:/…",
"wasohope RT @ASTERHealthcare: Omicron covid-19 variant was reported from South Africa on November 2021. This variant has had many mutations that aff…",
"SVictor70973566 RT @MdFacep: @EricTopol @maxdkozlov Omicron's impact is in its ability to evade our immune system: Our 'older' vaccine produced NABS fail…",
"Wildantlers @melulater Of course it did, Omicron spreads far quicker. But as a % of people who die from omicron it is far milde… https://t.co/eDFuW5qjAH",
"peterandann RT @EnemyInAState: Omicron, London: Babies and toddlers continue to surge, and 1 in 9 admitted is a child. Over 668 babies and toddlers hav…",
"DrMroz RT @CIHR_IRSC: In light of the disruptions caused by the Omicron variant of #Covid19, CIHR is extending the registration and application de…",
"Deis85208721 CORRECTED-Japan's Kowa says ivermectin showed 'antiviral effect' against Omicron in research https://t.co/VEoQyz5x6F",
"freethinkfacts RT @yaneerbaryam: Thus, breakthrough infection from Omicron may enhance cross-protection against Delta, and vice-versa, [only] inasmuch as…"]


In [30]:
import numpy as np

vectorizer = CountVectorizer(stop_words='english', ngram_range=(2, 2), min_df=2)
X = vectorizer.fit_transform(corpus)
#print("stop words removed:", vectorizer.stop_words_)
words = vectorizer.get_feature_names_out()
print(f"#words {len(words)} {words}")

#words 22 ['antiviral effect' 'caused omicron' 'cihr extending' 'cihr_irsc light'
 'covid19 cihr' 'disruptions caused' 'effect omicron'
 'extending registration' 'freethinkfacts rt' 'ivermectin showed'
 'japan kowa' 'kowa says' 'light disruptions' 'omicron variant'
 'registration application' 'rt cihr_irsc' 'rt erictopol'
 'rt yaneerbaryam' 'says ivermectin' 'showed antiviral'
 'svictor70973566 rt' 'variant covid19']


In [5]:
X_array = X.toarray()
print(X_array)

[[0 1 1 1 1 1 0 1 0 0 0 0 1 1 1 1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1 0 0 1 1 1 0 0 0 0 0 0 1 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 1 1 1 1 1 0 1 0 0 0 0 1 1 1 1 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 0 1 0 0 0 0 1 1 1 1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1 0 0 1 1 1 0 0 0 0 0 0 1 1 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0]]


In [14]:
# Coverting features into hashed values but in binary format

import hashlib

hashedbin = list()
for word in words:
    word = word.encode('utf-8')
    binword = bin(int.from_bytes(hashlib.sha256(word).digest(), 'little'))[-64:]
    print(binword)
    hashedbin.append([*binword])

1011010011001011100010111010111000100101110011001110101101000010
0001101101011010011011001110110101101110010111011111100010000010
0101111111011000100010110000010011000010110000010111100001000001
1010100111010101000001101111010010110000001101010111111111010111
1100010101000100110011001001000111110110100010111001010110011011
1111101010001011010111001110100110110011100111000110100011001010
0111011011001100111111110111111010110101001100100000111001110001
0100011101101011110110011000110000001001010011111000110111001001
1111010111101101011011001010101010001101100001010000001111101111
0111111000101101011100111101010101101100101000001101111110001100
1000010000101010001000110111110010000011001010111011011101110111
1101000011100101101011001110100100011110110101000011100101111111
1011001000000110010001111001011001010011111010001101110101010010
0010101000011100010111011100110110011111101011010000001000000101
1111111010100010010101110101001101000010010001111001111001100110
1001101111000100110011000

# SimHashing

In [17]:
SIMHASH = [0]*len(X_array)
for doc in range(len(X_array)):
    document = X_array[doc]
    hash = list()
    for col in range(0,64):
        addCol = 0
        for row in range(len(hashedbin)):
            binvalue = int(hashedbin[row][col])
            if binvalue == 1:
                addCol += binvalue*document[row]
            else:
                addCol -= 1*document[row]
        if addCol < 0:
            addCol = 0
        else:
            addCol = 1
        hash.append(addCol)
    SIMHASH[doc] = hash
print(*SIMHASH,sep='\n')
            

[1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1]
[1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1]
[1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1]
[1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1]
[1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

# Calculating the similarity matrix for haming distance and euclidean distance

In [27]:
import math

Hamming = list()
Euclidean = list()
for simHash1 in simHashes:
    Hamming_Similarity = list()
    Euclidean_Similarity = list()
    for simHash2 in simHashes:
        distance = 0
        for col in range(len(simHash1)):
            if simHash1[col] == simHash2[col]:
                distance += 1
        Hamming_Similarity.append(64-distance)
        
        point1 = X_array[simHashes.index(simHash1)]
        point2 = X_array[simHashes.index(simHash2)]

        Euclidean_Similarity.append(round(math.dist(point1, point2),2))

    Euclidean.append(Euclidean_Similarity)
    Hamming.append(Hamming_Similarity)
print("Similarity matrix of Hamming distance")
print(*Hamming,sep='\n')

print("Similarity matrix of Euclidean distance")
print(*Euclidean,sep='\n')

Similarity matrix of Hamming distance
[0, 39, 26, 30, 0, 29, 30, 29, 29, 23, 29, 29, 0, 39, 30]
[39, 0, 31, 29, 39, 24, 29, 32, 24, 34, 24, 24, 39, 0, 29]
[26, 31, 0, 22, 26, 15, 22, 21, 15, 13, 15, 15, 26, 31, 22]
[30, 29, 22, 0, 30, 11, 0, 41, 11, 25, 11, 11, 30, 29, 0]
[0, 39, 26, 30, 0, 29, 30, 29, 29, 23, 29, 29, 0, 39, 30]
[29, 24, 15, 11, 29, 0, 11, 36, 0, 28, 0, 0, 29, 24, 11]
[30, 29, 22, 0, 30, 11, 0, 41, 11, 25, 11, 11, 30, 29, 0]
[29, 32, 21, 41, 29, 36, 41, 0, 36, 34, 36, 36, 29, 32, 41]
[29, 24, 15, 11, 29, 0, 11, 36, 0, 28, 0, 0, 29, 24, 11]
[23, 34, 13, 25, 23, 28, 25, 34, 28, 0, 28, 28, 23, 34, 25]
[29, 24, 15, 11, 29, 0, 11, 36, 0, 28, 0, 0, 29, 24, 11]
[29, 24, 15, 11, 29, 0, 11, 36, 0, 28, 0, 0, 29, 24, 11]
[0, 39, 26, 30, 0, 29, 30, 29, 29, 23, 29, 29, 0, 39, 30]
[39, 0, 31, 29, 39, 24, 29, 32, 24, 34, 24, 24, 39, 0, 29]
[30, 29, 22, 0, 30, 11, 0, 41, 11, 25, 11, 11, 30, 29, 0]
Similarity matrix of Euclidean distance
[0.0, 4.24, 3.61, 3.61, 0.0, 3.32, 3.61, 3.46, 3

# Computing the Pearson Correlation of the distances between all pairs of documents

In [34]:
Hamming_array = np.array(Hamming).flatten()
Euclidean_array = np.array(Euclidean).flatten()
pearson_correlation = np.corrcoef(Hamming_array, Euclidean_array)

print("The pearson correlation between the distances for all pairs of documents = \n", pearson_correlation)

The pearson correlation between the distances for all pairs of documents = 
 [[1.         0.79289978]
 [0.79289978 1.        ]]
